
default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
        name: ruff (lint + fix)
        args: [--fix]
        files: ^app/
        types_or: [python]

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        name: black (format)
        files: ^app/
        types_or: [python]

