# low <-> mid
listener 1883 0.0.0.0
protocol mqtt

# mid <-> high
listener 9001
protocol websockets

# For test
allow_anonymous true

# allow_anonymous false
# password_file /mosquitto/config/passwd
# acl_file /mosquitto/config/acl

persistence true
persistence_location /mosquitto/data/
log_type error
log_type warning
log_type notice
log_type information
